# Generated by Django 2.2.17 on 2021-02-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to='movies/'),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='people/'),
        ),
    ]
